# Generated by Django 5.2.1 on 2025-08-26 10:06

from collections.abc import Sequence
from typing import ClassVar

from django.db import migrations
from django.db.migrations.operations.base import Operation

from maykin_common.migration_operations import ResetSequences


class Migration(migrations.Migration):
    dependencies: ClassVar[Sequence[tuple[str, str]]] = []

    operations: ClassVar[Sequence[Operation]] = [
        ResetSequences(),
    ]
